#include"header.h"
#define SI ((I2CONSET>>3)&1)
#define STA (1<<5)
#define STO (1<<4)

void i2c_init(void){
	PINSEL0|=0X50;//P0.2->SCL & P0.3->SCA
	I2CONSET=(1<<6);//SELECT MSTR MODE I2EN=1
	I2SCLL=I2SCLH=75;//SET FREQUENCY TO 100KB/PS STANDARD MODE
}

void i2c_write(u8 sa,u8 addr,u8 data){
	/*1)GENERATE START CONDITION*/
		I2CONSET=1<<5;//SET STA=1
		I2CONCLR=1<<3;//CLEAR SI FLAG
		while(SI==0);//WAIT TO TRANSMIT START CONDITION
		I2CONCLR=1<<5;//CLEAR STA=0
	
	/*2)SEND SLAVE ADDRESS+WRITE & WAIT FOR ACK(STATUS CODE=0X20)*/
		I2DAT=sa;//SEND SA+W
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);//WAIT TO TRANSMIT SA+W 
		if(I2STAT==0X20){
			uart0_str("\r\nERROR:SA+W");//CHECK ACK
			goto exit;
		}
		
	/*3)SEND MR.ADDR & WAIT FOR ACK(STATUS CODE=0X30)*/
		I2DAT=addr;//SEND MR.ADDR
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);//WAIT TO TRANSMIT MR.ADDR 
		if(I2STAT==0X30){
			uart0_str("\r\nERROR:MR.ADDR");//CHECK FOR ACK
			goto exit;
		}
			
	/*4)SEND DATA & WAIT FOR ACK(STATUS CODE=0X0X30)*/
		I2DAT=data;//SEND DATA
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);//WAIT TO TRANSMIT DATA
		if(I2STAT==0X30){
			uart0_str("\r\nERROR:DATA");
			goto exit;
		}
		exit:	
	/*5)GENERATE STOP CONDITION*/
		I2CONSET=STO;//SET STO=1
		I2CONCLR=1<<3;//CLEAR SI
}

u8 i2c_read(u8 sa,u8 addr){
		u8 result=0;
	/*1)GENERATE START CONDITION*/
		I2CONSET=STA;//GENERATE START CONDITION
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);//WAIT TO TRANSMIT START CONDITION
		I2CONCLR=STA;//CLEAR START
	
	/*2)SEND SA+WRITE & WAIT FOR ACK(STATUS CODE=0X20)*/
		I2DAT=sa&0xFE;//MAKE 0TH BIT AS 0 TO SEND SA+W
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);//WAIT TO TRANSMIT SA+W
		if(I2STAT==0X20){
			uart0_str("\r\nERROR:SA+W");//CHECK ACK
			goto exit;
		}
		
	/*3)SEND MR.ADDDR & WAIT FOR ACK(STATUS CODE=0X30)*/
		I2DAT=addr;//SEND MR.ADDR
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);
		if(I2STAT==0X30){
			uart0_str("\r\nERROR:MR.ADDR");
			goto exit;
		}
		
	/*4)GENERATE RESTART*/
		I2CONSET=STA;//GENERATE START CONDITION
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);//WAIT TO TRANSMIT START CONDITION
		I2CONCLR=STA;//CLEAR STA
		
	/*5)SEND SA+READ & WAIT FOR ACK(STATUS CODE=0X20)*/
		I2DAT=sa;//SEND SA+READ
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);
		if(I2STAT==0X20){
			uart0_str("\r\nERROR:SA+R");
			goto exit;
		}
		
	/*6)READ DATA FROM SLAVE AND SEND NO ACK*/
		I2CONCLR=1<<3;//CLEAR SI
		while(SI==0);
		result=I2DAT;
	
	/*7)GENERATE STOP CONDITION*/
		exit:
		I2CONSET=STO;//SEND STOP CONDITION
		I2CONCLR=1<<3;//CLEAR SI
		
	/*8)RETURN RESULT*/
		return result;
}
